-- Add migration script here
CREATE TABLE IF NOT EXISTS res_type (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS res (
    id TEXT PRIMARY KEY,
    tid TEXT NOT NULL,
    aid TEXT NOT NULL,
    num UNSIGNED INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS activity (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    num UNSIGNED INTEGER NOT NULL DEFAULT 0,
    consume UNSIGNED INTEGER NOT NULL DEFAULT 0
);